allow_remote_control yes
listen_on unix:@mykitty
font_size 14.0
font_family JetBrainsMono Nerd Font
background_opacity 1
background_blur 100
confirm_os_window_close 0

# BEGIN_KITTY_THEME
# Cherry Midnight
include ~/.cache/wal/colors-kitty.conf
# END_KITTY_THEME
